package com.fulfilment.application.monolith.exceptions;


public enum ErrorCode {
    BODYMISSING,
    FIELDISREQUIRED,

    WAREHOUSEALREADYEXIST,
    WAREHOUSENOTFOUND,

    MAXWAREHOUSENUMBERREACHED,

    WAREHOUSELOCATIONEXCEEDEDMAXCAPACITY,
    BUSINESSUNITCODENOTMATCH,
    WAREHOUSEPREVIOUSLYARCHIVED,
    INSUFFICIENTWAREHOUSECAPACITY,
    WAREHOUSESTOCKMISMATCH

}
